# Generated by Django 4.1.3 on 2023-01-13 17:13

from django.db import migrations, models
import django_express.tools.cpf_validator


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django_express.tools.cpf_validator.Cpfvalidator]),
        ),
    ]
