# Generated by Django 4.1.3 on 2023-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0002_alter_deliverer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
